### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by Chetan-KK** [anurag12-webster/MP-Project2#1]
after installation this deprecated error is poping up

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

## upgrader it to newer version

![Untitled](https://github.com/anurag12-webster/MP-Project2/assets/44507196/ee6796d9-cbda-4be9-9950-39d24c164aeb)
![2](https://github.com/anurag12-webster/MP-Project2/assets/44507196/2dcdba4d-ec44-48ee-9872-3d1ed06653de)

**Comment by anurag12-webster** [comment]
Merged and Closed
